this.gcal=this.gcal||{};(function(_){var window=this;
try{
_._F_toggles_initialize=function(a){("undefined"!==typeof globalThis?globalThis:"undefined"!==typeof self?self:this)._F_toggles=a||[]};(0,_._F_toggles_initialize)([0xc0, ]);
/*

 SPDX-License-Identifier: Apache-2.0
*/
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var f=function(a){if(a instanceof e)a=a instanceof e&&a.constructor===e?a.h:"type_error:SafeUrl";else{b:{try{var b=new URL(a)}catch(c){b="https:";break b}b=b.protocol}a="javascript:"!==b?a:void 0}return a},k=function(a,b){a.removeAttribute("srcdoc");if(b instanceof g)throw new h("TrustedResourceUrl",3);var c="allow-same-origin allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox allow-storage-access-by-user-activation".split(" ");a.setAttribute("sandbox","");for(let d=0;d<c.length;d++)a.sandbox.supports&&
!a.sandbox.supports(c[d])||a.sandbox.add(c[d]);b=f(b);void 0!==b&&(a.src=b)},m=function(a,b){if(b instanceof g)a.href=(b instanceof g&&b.constructor===g?b.i:"type_error:TrustedResourceUrl").toString();else{if(-1===l.indexOf("stylesheet"))throw Error("b`stylesheet");b=f(b);if(void 0===b)return;a.href=b}a.rel="stylesheet"},p=function(a,...b){if(0===b.length)return n(a[0]);let c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return n(c)},q=function(){const a=document.createElement("span");
a.textContent="close";a.classList.add("material-icons");a.classList.add("L0Dvsd");const b=document.createElement("div");b.textContent="Close";b.classList.add("uE25ec");const c=document.createElement("button");c.appendChild(a);c.appendChild(b);c.classList.add("Xfsokf");return c},t=function(a,b){var c=q();r=document.createElement("div");r.classList.add("hur54b");r.appendChild(c);r.appendChild(a);c.onclick=()=>{r&&(r.remove(),r=null);b.focus()};r.onclick=()=>{r&&(r.remove(),r=null);b.focus()};return r},
u=function(a,b){const c=document.createElement("iframe");c.title=b;c.classList.add("mmGMM");k(c,a);c.onload=()=>{c.contentWindow.focus()};return c},y=function(a){const b=document.createElement("button");b.textContent=a.label;b.style.color=v(w(x(a.color)));b.style.backgroundColor=a.color;b.classList.add("qxCTlb");b.onclick=()=>{const c=document.body,d=t(u(a.url,a.label),b);c.appendChild(d)};return b},z="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},
A;if("function"==typeof Object.setPrototypeOf)A=Object.setPrototypeOf;else{var B;a:{var C={a:!0},D={};try{D.__proto__=C;B=D.a;break a}catch(a){}B=!1}A=B?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError("a`"+a);return a}:null}var E=A;var F=this||self,G=function(a){return a};var H;var g=function(a){this.i=a};g.prototype.toString=function(){return this.i+""};var I={},n=function(a){if(void 0===H){var b=null;var c=F.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:G,createScript:G,createScriptURL:G})}catch(d){F.console&&F.console.error(d.message)}H=b}else H=b}a=(b=H)?b.createScriptURL(a):a;return new g(a,I)};var e=function(a){this.h=a};e.prototype.toString=function(){return this.h.toString()};var J={m:0,o:1,j:2,l:3,0:"FORMATTED_HTML_CONTENT",1:"HTML_FORMATTED_CONTENT",2:"EMBEDDED_INTERNAL_CONTENT",3:"EMBEDDED_TRUSTED_EXTERNAL_CONTENT"},h=function(a,b){b=Error.call(this,`${a} cannot be used with intent ${J[b]}`);this.message=b.message;"stack"in b&&(this.stack=b.stack);this.type=a;this.name="TypeCannotBeUsedWithIntentError"},K=Error;h.prototype=z(K.prototype);h.prototype.constructor=h;
if(E)E(h,K);else for(var L in K)if("prototype"!=L)if(Object.defineProperties){var M=Object.getOwnPropertyDescriptor(K,L);M&&Object.defineProperty(h,L,M)}else h[L]=K[L];var l="alternate author bookmark canonical cite help icon license modulepreload next prefetch dns-prefetch prerender preconnect preload prev search subresource".split(" ");var N=!1,O=!1;var r;var P=/#(.)(.)(.)/,x=function(a){if(!Q.test(a))throw Error("c`"+a);4==a.length&&(a=a.replace(P,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},v=function(a){var b=a[0],c=a[1];a=a[2];b=Number(b);c=Number(c);a=Number(a);if(b!=(b&255)||c!=(c&255)||a!=(a&255))throw Error("d`"+b+"`"+c+"`"+a);c=b<<16|c<<8|a;return 16>b?"#"+(16777216|c).toString(16).slice(1):"#"+c.toString(16)},Q=/^#(?:[0-9a-f]{3}){1,2}$/i,w=function(a){var b=[R,S];const c=[];for(let d=0;d<b.length;d++)c.push({color:b[d],
g:Math.abs(T(b[d])-T(a))+U(b[d],a)});c.sort(function(d,V){return V.g-d.g});return c[0].color},T=function(a){return Math.round((299*a[0]+587*a[1]+114*a[2])/1E3)},U=function(a,b){return Math.abs(a[0]-b[0])+Math.abs(a[1]-b[1])+Math.abs(a[2]-b[2])};var R=x("#ffffff"),S=x("#000000");window.calendar=window.calendar||{};window.calendar.schedulingButton={load:function(a){var b=a.target;a=y(a);b.insertAdjacentElement("afterend",a);N||(b=document.createElement("link"),m(b,p`https://fonts.googleapis.com/css?family=Google+Sans:400,500`),document.head.appendChild(b));N=!0;O||(b=document.createElement("link"),m(b,p`https://fonts.googleapis.com/icon?family=Material+Icons`),document.head.appendChild(b));O=!0}};
}catch(e){_._DumpException(e)}
})(this.gcal);
// Google Inc.
